root/main/models.py
from root import db, login_manager
from root.main.utils import localTime
from flask_login import UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):

    __tabelname__ = 'user'
    
    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(db.String, unique=True)
    
    username = db.Column(db.String(20), unique=True)
    password = db.Column(db.String(100)) 
    email = db.Column(db.String(80), unique=True)

    is_confirmed = db.Column(db.Boolean, default=False) # --> NOT REQUIRED FOR THIS PROJECT.

    # is_su = db.Column(db.Boolean, default='False') ---> DEPRECATED.
    is_admin = db.Column(db.Boolean, default=False)

    timestamp = db.Column(db.DateTime, nullable=False, default=localTime())

class LicenseKey(db.Model):
   
    __tabelname__ = 'license_key'
    
    id = db.Column(db.Integer, primary_key=True)
    key = db.Column(db.String, unique=True)
    status = db.Column(db.String, default='NEW')

    timestamp = db.Column(db.DateTime, nullable=False, default=localTime())


class DeviceReg(db.Model):
   
    __tabelname__ = 'device_reg'
   
    id = db.Column(db.Integer, primary_key=True)
    business_type = db.Column(db.String)
    uuid = db.Column(db.String, unique=True)
    serial_number = db.Column(db.String, unique=True)
    baseboard_serial_number = db.Column(db.String, unique=True)
    license_key = db.Column(db.String)

    timestamp = db.Column(db.DateTime, nullable=False, default=localTime())

root/main/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, request, render_template, redirect, url_for, flash, jsonify
from flask_login import login_required, login_user, current_user, logout_user

from root import create_app, db, bcrypt
from root.main.utils import uuid_url64, generate_auth_token, auth_token_required, CrudUser
from root.main.models import DeviceReg, LicenseKey, User

main = Blueprint("main", __name__, template_folder="templates")

# REMOVE WHEN DONE
# REMOVE WHEN DONE
# REMOVE WHEN DONE

@main.route('/test', methods=['POST', 'GET'])
@auth_token_required
def tests():

    if request.method == 'GET':

        u = User.query.all()

        if u:

            for i in u:

                print(i)
        else:

            print('NO USERS NIBBA')

    return 'SUCCESS'

@main.route('/t', methods=['POST']) # <--- JS
def __get_token():

    auth_token_request = request.json['GET_AUTH_TOKEN_5']

    if auth_token_request:

        t = generate_auth_token(5)

        return jsonify({
            'status': t
        })

    else:

        return jsonify({
            'status': 'NOT FOUND'
        })


@main.route('/r')
def reset_db():

    try:

        app = create_app()

        db.drop_all()
        db.create_all(app=app)

        keys = LicenseKey.query.first()

        if keys:

            return 'KEYS EXISTS.'

        counter = 1

        while counter < 100:

            unique_key = uuid_url64()
            new_license_key = LicenseKey(key=unique_key)

            db.session.add(new_license_key)
            db.session.commit()

            counter += 1

        crud = CrudUser()

        crud.create_user('admin', '0000')

        print('DB RESET >> DONE')
        print('CREATE ADMIN >> DONE')
        print('GENERATING LICENSE KEYS >> DONE')

    except Exception as e:

        print(e)

    logout_user()
    flash('OPERATION DONE. CHECK APP LOGS FOR DETAILES.', 'success')
    return redirect(url_for('main.login'))


# REMOVE WHEN DONE
# REMOVE WHEN DONE
# REMOVE WHEN DONE


# VERIFY LICESNSE ( AUTH TOKEN REQUIRED )

@main.route('/api/verify_license', methods=['POST'])
@auth_token_required
def verify_license():

    # SYS INFO

    device_uuid = request.json['device_uuid']
    device_serial_number = request.json['device_serial_number']
    device_baseboard_serial = request.json['device_baseboard_serial']
    license_key = request.json['license_key']

    # CHECK IF LICENSE IS VALID

    print('VALIDATING LICESNSE...')

    valid_license = LicenseKey.query.filter_by(key=license_key).first()

    if valid_license:  # <-------- [ LICENSE IS VALID ]

        # CHECK IF DEVICE IS REGISTERED.

        print('LICENSE IS VALID. CHECKING IF THE DEVICE IS REGISTERED.')

        is_registered_device = DeviceReg.query.filter_by(
            uuid=device_uuid).first()

        if is_registered_device:  # <-------- [ ALREADY REGISTERED ] [ R-1 ]

            print('ALREADY REGISTERED.')
            return 'R-1'

        else:  # <-------- [ NOT REGISTERED ]

            # CHECK IF LICENSE IS USED BY ANOTHER DEVICE.

            print('CHECKING IF LICENSE IS USED...')

            # <-------- [ USED LICENSE ] [ R-2 ]
            if valid_license.status == 'USED':

                print('USED LICENSE.')
                return 'R-2'

            else:  # LICENSE STATUS == NEW

                print('LICENSE IS VALID. REGISTERING DEVICE...')

                new_device_reg = DeviceReg(uuid=device_uuid, serial_number=device_serial_number, baseboard_serial_number=device_baseboard_serial,
                                           license_key=license_key)

                valid_license.status = 'USED'

                db.session.add(new_device_reg)
                db.session.commit()

                print('DEVICE REGISTERED SUCCESSFULLY.')
                # <-------- [ DEVICE REGISTERED SUCCESSFULLY ] [ R-3 ]
                return 'R-3'

    else:

        print('LICENSE NOT VALID.')
        return 'R-4'  # <-------- [ LICENSE NOT VALID ] [ R-4 ]


@main.route('/')
@login_required
def index():

    keys = LicenseKey.query.all()
    regs = DeviceReg.query.all()

    return render_template('/main/index.html', regs=regs, keys=keys)


@main.route('/login', methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:

        return f'{current_user.username} IS ALREADY LOGGED IN.'

    if request.method == 'POST':

        user = User.query.filter_by(username=request.form['username']).first()

        if user is None:

            return 'USER DOES NOT EXIST'

        elif not bcrypt.check_password_hash(user.password, request.form['password']):

            return 'CHECK YOUR PASSWORD'

        elif user and bcrypt.check_password_hash(user.password, request.form['password']):

            login_user(user)

            return redirect(url_for('main.index'))

    return render_template('/main/login.html')


@main.route('/logout')
def logout():

    logout_user()

    return 'LOGGED OUT.'

root/main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>P.L.C.A - INDEX</title>

    <!-- js -->

    <script src="{{ url_for('static', filename='js/pkgs/jquery-1.11.3.min.js') }}"></script>

    <!-- css -->

    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">

</head>

<body>

    <span class="center" style="top: 30px !important; font-weight: 600; color: white; font-size: 25px;"> PY POS LICENSE
        VERIFICATION </span>

    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        a {
            color: black;
            text-align: center;
        }

        table,
        th,
        td {
            text-align: center;
            border: 1px solid black;
            font-size: 20px;
        }

        td {
            padding: 10px;
        }

        table {
            width: 90%;
        }
    </style>

    <script>
        $(document).ready(function () {

            $('.copy').click(function (e) {
                e.preventDefault();
                var $temp = $("<input>");
                $("body").append($temp);
                $temp.val($(this).parent().find('span').text()).select();
                $(this).css('background-color', 'green')
                $(this).text('COPIED')
                document.execCommand("copy");
                $temp.remove();
            });

            $('#list_keys_toggle').click(function (e) {
                e.preventDefault();
                $('#regs_table_wrpr').css('display', 'none')
                $('#keys_table_wrpr').css('display', 'flex')
            });

            $('#list_regs_toggle').click(function (e) {
                e.preventDefault();
                $('#keys_table_wrpr').css('display', 'none')
                $('#regs_table_wrpr').css('display', 'flex')
            });

            $('#auth_token').click(function (e) {
                e.preventDefault();

                $.ajax({
                    type: "POST",
                    url: '/t',
                    dataType: 'json',
                    contentType: 'application/json;charset=UTF-8',
                    data: JSON.stringify({
                        'GET_AUTH_TOKEN_5': '1'
                    }),
                    success: (r) => {

                        let auth_token = r['status']

                        var $temp = $("<input>");
                        $("body").append($temp);
                        $temp.val(auth_token).select();
                        document.execCommand("copy");
                        $temp.remove();
                        alert('AUTH TOKEN COPIED.')

                    },
                    error: () => {
                        alert('error')
                    }
                })

            });

        });
    </script>

    <div class="box-shadow flex-c-se" style="width: 95%; height: 80%; background-color: #ffffff81;">
        <!-- OUTER WRPR -->

        <div class="wh100 flex-c-c">
            <!-- INNER LEFT WRPR -->

            <div id="regs_table_wrpr" class="wh100" style="overflow-y: auto; display: none;">
                <!-- REGS WRPR -->

                <table class="w100" style="height: 30px;">

                    <tr style="height: 30px;">

                        <th>LICENSEKEY</th>
                        <th>BASEBOARD_SERIAL_NUMBER</th>
                        <th>SERIAL_NUMBER</th>
                        <th>UUID</th>
                        <th>النشاط</th>

                    </tr>

                    {% if regs %}

                    {% for device in regs %}

                    <tr>
                        <td>{{ device.license_key }}</td>
                        <td>{{ device.baseboard_serial_number }}</td>
                        <td>{{ device.serial_number }}</td>
                        <td>{{ device.uuid }}</td>
                        <td>{{ device.business_type }}</td>
                    </tr>

                    {% endfor %}

                    {% endif %}

                </table>

            </div>

            <div id="keys_table_wrpr" class="wh100" style="overflow-y: auto;">
                <!-- KEYS WRPR -->

                <table class="w100">

                    <tr style="height: 30px;">
                        <th>STATUS</th>
                        <th>LICENSEKEY</th>
                    </tr>

                    {% for key in keys %}

                    {% if key.status == 'USED' %}

                    <tr style="background-color: red;">
                        <td>{{ key.status }}</td>
                        <td class="flex-c-sb" style="padding-left: 5px;"> <span
                                style="text-align: center; width: 90%;">{{ key.key }}</span> <a href="#" class="btn blue_btn copy"
                                style="font-size: small; width: auto; height: auto; padding: 3px 7px;">COPY</a> </td>
                    </tr>

                    {% else %}

                    <tr>
                        <td>{{ key.status }}</td>
                        <td class="flex-c-sb" style="padding-left: 5px;"> <span
                                style="text-align: center; width: 90%;">{{ key.key }}</span> <a href="#" class="btn blue_btn copy"
                                style="font-size: small; width: auto; height: auto; padding: 3px 7px;">COPY</a> </td>
                    </tr>

                    {% endif %}

                    {% endfor %}

                </table>

            </div>


        </div>

        <div style="width: 30% !important;" class="h100 flex-c-c-se box-shadow">
            <!-- INNER RIGHT WRPR -->

            <a id="list_keys_toggle" class="btn trans_btn" style="width: 250px; padding: 0 10px;" href="#">LIST KEYS</a>
            <a id="list_regs_toggle" class="btn trans_btn" style="width: 250px; padding: 0 10px;" href="#">LIST
                REGISTRIES</a>
            <a id="auth_token" class="btn trans_btn" style="width: 250px; padding: 0 10px;" href="#">AUTH TOKEN ( 5m
                )</a>
            <a class="btn red_btn" style="width: 250px; padding: 0 10px;" href="{{ url_for('main.reset_db') }}">RESET DB
                ( DEV OPTION )</a>

        </div>

    </div>

</body>

</html>

root/main/templates/main/login.html
<!DOCTYPE html>
<html lang="en">
    
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">

</head>

<body>

    <span class="w100 center" style="text-align: center; top: 140px; font-size: 40px; color: white;">PYPOS LICENSE CHECK API - LOGIN</span>

    <form style="width: 300px; height: 300px;" class="center flex-c-c-se" action="/login" method="post">

        <input style="padding: 5px 15px;" type="text" name="username" placeholder="USERNAME">
        <input style="padding: 5px 15px;" type="password" name="password" placeholder="PASSWORD">

        <button type="submit" class="btn blue_btn">LOGIN</button>

    </form>

    {% with messages = get_flashed_messages(with_categories=true) %}
    
        {% if messages %}
        
            {% for category, message in messages %}

            <div id="flash-msg" class="alert alert-{{ category }} flex-c-c">

                <span class="w100 flex-c-c" style="height: 100%;">{{ message }}</span>
                
            </div>

            {% endfor %}

        {% endif %}

    {% endwith %}
    
</body>

</html>